apiVersion: sources.knative.dev/v1alpha1
kind: GitHubSource
metadata:
  name: endgamesource
  namespace: integration
spec:
  eventTypes:
    - pull_request
    - issue_comment
  ownerAndRepository: inspirit941/knative-eventing-example
  accessToken:
    secretKeyRef:
      name: githubsecret
      key: accessToken
  secretToken:
    secretKeyRef:
      name: githubsecret
      key: secretToken
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: github-message-dumper
      namespace: dev
