apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: github-message-dumper
  namespace: dev
spec:
  template:
    spec:
      containers:
        - image: idock.daumkakao.io/test-210722/test-gcr-image
