apiVersion: v1
data:
  bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092
  eventing-kafka: |
    kafka:
      brokers: my-cluster-kafka-bootstrap.kafka:9092

kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"bootstrapServers":"my-cluster-kafka-bootstrap.kafka:9092"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"config-kafka","namespace":"knative-eventing"}}
  creationTimestamp: "2022-03-06T05:54:31Z"
  name: config-kafka
  namespace: knative-eventing
  resourceVersion: "125070879"
  selfLink: /api/v1/namespaces/knative-eventing/configmaps/config-kafka
  uid: 1b9724a8-8af4-41c1-a8cd-c019e6fbdfdf
